services:
  nginx:
    container_name: qter_nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx/:/etc/nginx/conf.d/"
  mongo:
    container_name: qter_mongo
    image: mongo:7.0.14
    volumes:
      - qter-auth-mongo-data:/data/db
  auth:
    container_name: qter_auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: production
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/users
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - JWT_SECRET=fsalkdjfsdkfhslkfjs
      - JWT_EXPIRATION=90d
  quotes:
    container_name: qter_quotes
    build:
      context: .
      dockerfile: ./apps/quotes/Dockerfile
      target: production
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongo:27017/quotes
      - RABBITMQ_URI=amqp://rabbitmq:5672
  search:
    container_name: qter_search
    build:
      context: .
      dockerfile: ./apps/search/Dockerfile
      target: production
    environment:
      - PORT=3003
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - ELASTIC_URI=http://elasticsearch:9200
  rabbitmq:
    container_name: qter_rabbitmq
    image: rabbitmq:4.0.2-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: qter_es
    environment:
      - node.name=es01
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false # Disable security for basic setup (username/password auth)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: qter_kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  qter-auth-mongo-data:
  esdata:
  rabbitmq-data:
