apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - http:
      paths:
      - path: /auth
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.auth.name }}
            port:
              number: {{ .Values.auth.port }}
      - path: /users
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.auth.name }}
            port:
              number: {{ .Values.auth.port }}
      - path: /quotes
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.quotes.name }}
            port:
              number: {{ .Values.quotes.port }}
      - path: /search
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.search.name }}
            port:
              number: {{ .Values.search.port }}
