apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.search.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.search.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.search.name }}
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  search
      labels:
        app: {{ .Values.search.name }}
    spec:
      containers:
      - name: {{ .Values.search.name }}
        image: masterj3y/qter-search:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: HTTP_PORT 
          value: {{ .Values.search.httpPort | quote }}
        - name: TCP_PORT 
          value: {{ .Values.search.tcpPort | quote }}
        - name: AUTH_HOST
          value: auth-tcp
        - name: AUTH_PORT
          value: {{ .Values.auth.tcpPort | quote }}
        - name: ELASTIC_HOST 
          value: qter-elasticsearch
        - name: ELASTIC_PORT 
          value: "9200"
        ports:
        - containerPort: {{ .Values.search.httpPort }}
        - containerPort: {{ .Values.search.tcpPort }}
