apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.search.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.search.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.search.name }}
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  search
      labels:
        app: {{ .Values.search.name }}
    spec:
      containers:
      - name: {{ .Values.search.name }}
        image: masterj3y/qter-search:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: PORT 
          value: {{ .Values.search.port | quote }}
        - name: RABBITMQ_URI
          value: "amqp://qter-rabbitmq:5672"
        - name: ELASTIC_URI
          value: "http://qter-elasticsearch:9200"
        ports:
        - containerPort: {{ .Values.search.port }}
