apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.search.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.search.name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.search.port }}
    targetPort: {{ .Values.search.port }}
