apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.quotes.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.quotes.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.quotes.name }}
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  quotes
      labels:
        app: {{ .Values.quotes.name }}
    spec:
      containers:
      - name: {{ .Values.quotes.name }}
        image: "{{ .Values.quotes.image }}:{{ .Values.quotes.imageTag }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: PORT
          value: {{ .Values.quotes.port | quote }}
        - name: MONGODB_URI
          value: {{ .Values.quotes.mongoDbUri }}
        - name: RABBITMQ_URI
          value: "amqp://qter-rabbitmq:5672"
        ports:
        - containerPort: {{ .Values.quotes.port }}
        livenessProbe:
          httpGet:
            path: /quotes/liveness/check
            port: {{ .Values.quotes.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /quotes/readiness/check
            port: {{ .Values.quotes.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
---

