name: Docker Image CI/CD

on:
  push:
    branches: 
      - main
    paths:
      - '.github/workflows/**'
      - 'backend/apps/**'
      - 'backend/libs/**'
      - 'backend/package-lock.json'
      - 'backend/package.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'backend/apps/**'
      - 'backend/libs/**'
      - 'backend/package-lock.json'
      - 'backend/package.json'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Auth service
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./backend/apps/auth/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qter-auth:latest

      - name: Build and Push Quote service
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./backend/apps/quotes/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qter-quotes:latest

      - name: Build and Push Search service
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./backend/apps/search/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qter-search:latest
